name: crm
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  # sdk: ">=2.7.0 <3.0.0"
  sdk: ">=2.12.0 <3.0.0"



dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  http: ^0.13.5
  #text_tools: ^0.0.2
  #math_expressions: ^2.3.1
  easy_sidemenu: ^0.4.1
  #sidebarx: ^0.14.0
  #side_bar_custom: ^1.0.3
  #flutter_sidebar: ^0.3.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^6.0.4
  flutter_svg: ^1.1.6
  dropdown_button2: ^1.8.9
  async: ^2.9.0
  email_validator: ^2.1.17
  date_field: ^3.0.2
  syncfusion_flutter_datagrid: ^20.3.61
  carousel_slider: ^4.2.1
  flutter_image_slideshow: ^0.1.4
  google_fonts: ^3.0.1
  url_launcher: ^6.1.7
  flutter_linkify: ^5.0.2
  flutter_inappwebview: ^5.7.2+3
  responsive_builder: ^0.4.3
  #flutter_sidebar: ^0.3.1
  #material_color_utilities: ^0.1.5

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  #  - lib/assets/images/Sls_Admn.png
  #  - lib/assets/images/Sls_Mgr.png
  #  - lib/assets/images/Sls_Exe.png
   - lib/assets/images/Bnd.png
   - lib/assets/images/MF.png
   - lib/assets/images/In.png
   - lib/assets/images/Logo-top.png
   - lib/assets/images/Logo-btm.png
   - lib/assets/images/crm_logo.png
   - lib/assets/images/Main_Sld.png
   - lib/assets/images/SA.png
   - lib/assets/images/SM.png
   - lib/assets/images/SE.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto_Light
      fonts:
        - asset: lib/assets/fonts/Roboto-Light.ttf
  #         style: italic

    - family: Roboto_Thin
      fonts:
        - asset: lib/assets/fonts/Roboto-Thin.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

    - family: Roboto_Regular
      fonts:
        - asset: lib/assets/fonts/Roboto-Regular.ttf

    - family: Arial
      fonts:
        - asset: lib/assets/fonts/arial_bold.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
